### ISSUE TITLE
Allow for duplicated elements?

### ISSUE THREAD

**Issue by robertamezquita** [kevinrue/unisets#5]
Should BaseSets enforce that elements must not be duplicated? Right now it currently allows for duplicated elements. I guess this makes sense if you see multiple instances of X and have say different elementData for each of them, but wondering if this might cause problems downstream.

**Comment by kevinrue** [comment]
Whoops. Well spotted, I wrote the validity method a tad too fast. Hang tight.

**Comment by kevinrue** [comment]
closed by #18
